version: '3.8'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
        - "3306"
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - my-db:/var/lib/mysql
  backend:
    build:
      context: ./ticketfinder
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db
    profiles: ["api"]

volumes:
  my-db: