version: '3.8'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
        - "3306"
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: